# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=20)),
                ('tagline', models.CharField(max_length=60)),
                ('email_subject', models.CharField(blank=True, max_length=100)),
                ('email_boilerplate', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('distance', models.FloatField(null=True)),
                ('climbing', models.SmallIntegerField(null=True)),
                ('cue_sheet', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Ride')),
            ],
        ),
        migrations.CreateModel(
            name='RouteDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ride', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.Ride')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
            options={
                'ordering': ('date',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('length', models.FloatField(null=True, blank=True)),
                ('altitude', models.SmallIntegerField(null=True, blank=True)),
                ('avg_grade', models.FloatField(null=True, blank=True)),
                ('kom_time', models.TimeField(null=True, blank=True)),
                ('strava_name', models.CharField(blank=True, max_length=100)),
                ('strava_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='routesegment',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Segment'),
        ),
        migrations.AddField(
            model_name='route',
            name='segments',
            field=models.ManyToManyField(related_name='routes', through='routes.RouteSegment', to='routes.Segment'),
        ),
    ]
